# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 651e78054c8e2f9e4a8df476658cbe63d34f0628927b2f077eecb701373bb3d78742d0f960a560b99be220df29c049960101bfc67be06c3eebbb0899203a7830

test:
  secret_key_base: fee7d0cb20886c47f8e0ec94c5ae78446e45fb25a69f75134b797fe686ffc126913bea5ac7b586e5afae15e4795a94cc72b9271073f127463c98f8b4516b27df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
